/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/n2dhG6IGswI
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { PopoverTrigger, PopoverContent, Popover } from "@/components/ui/popover"
import { Calendar } from "@/components/ui/calendar"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { useState } from 'react';

const plantData = [{
  plantId: '01-1-C',
  type: 'type1',
  date: '2021-08-01',
  leaves: 1,
  leafSurfaceAreaList: [1.4]
}, {
  plantId: '02-1-C',
  type: 'type2',
  date: '2021-08-01',
  leaves: 2,
  leafSurfaceAreaList: [1.54, 2.32]
}, {
  plantId: '03-1-C',
  type: 'type3',
  date: '2021-08-01',
  leaves: 3,
  leafSurfaceAreaList: [2.54, 5.32, 8.9]
}, {
  plantId: '04-1-C',
  type: 'type4',
  date: '2021-08-02',
  leaves: 3,
  leafSurfaceAreaList: [2.57, 5.5, 9.0]
},
{
  plantId: '05-1-C',
  type: 'type4',
  date: '2021-08-02',
  leaves: 3,
  leafSurfaceAreaList: [2.57, 5.5, 9.0]
}];


export function DataPortal() {
  const [day, setDay] = useState(new Date());
  function handleDateClick(DatePickerSingleProps){
    //setDay(DayPickerSingleProps.onSelect())
  }

  return (
    <div className="grid gap-8">
      <Card>
        <CardHeader>
          <CardTitle>Select the Plant</CardTitle>
          <CardDescription>Select the plant you are inputting data for</CardDescription>
        </CardHeader>
        <CardContent>
          <Select>
            <SelectTrigger className="w-[240px]">
              <SelectValue placeholder="Select the Plant" />
            </SelectTrigger>
            <SelectContent>
              {plantData.map(plant =>  <SelectItem key={plant.plantId} value={plant.type}>{plant.plantId}</SelectItem>)}
            </SelectContent>
          </Select>
        </CardContent>
      </Card>
      <Card>
        <CardHeader>
          <CardTitle>Date of Entry</CardTitle>
          <CardDescription>Select the date of entry.</CardDescription>
        </CardHeader>
        <CardContent>
          <Popover>
            <PopoverTrigger asChild>
              <Button className="w-[240px] justify-start text-left font-normal" variant="outline">
                <CalendarDaysIcon className="mr-1 h-4 w-4 -translate-x-1" />
                Pick a date
              </Button>
            </PopoverTrigger>
            <PopoverContent align="start" className="w-auto p-0">
              <Calendar initialFocus mode="single" onSelect={handleDateClick}/>
            </PopoverContent>
          </Popover>
        </CardContent>
      </Card>
      <Card>
        <CardHeader>
          <CardTitle>Plant Data</CardTitle>
          <CardDescription>Enter your plant data here beautiful ;)</CardDescription>
        </CardHeader>
        <CardContent>
          <form className="grid gap-4">
            <div className="space-y-2">
              <Label htmlFor="name">Number of Leaves</Label>
              <Input id="name" placeholder="Enter Number of Leaves" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="name">Email</Label>
              <Input id="email" placeholder="Enter your email" type="email" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="phone">Phone Number</Label>
              <Input id="phone" placeholder="Enter your phone number" />
            </div>
          </form>
        </CardContent>
      </Card>
      <Card>
        <CardHeader>
          <CardTitle>Address Information</CardTitle>
          <CardDescription>Enter your address details.</CardDescription>
        </CardHeader>
        <CardContent>
          <form className="grid gap-4">
            <div className="space-y-2">
              <Label htmlFor="address">Address</Label>
              <Input id="address" placeholder="Enter your address" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="city">City</Label>
              <Input id="city" placeholder="Enter your city" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="postal">Postal Code</Label>
              <Input id="postal" placeholder="Enter your postal code" />
            </div>
          </form>
        </CardContent>
      </Card>
      
      
    </div>
  )
}


function CalendarDaysIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
      <path d="M8 14h.01" />
      <path d="M12 14h.01" />
      <path d="M16 14h.01" />
      <path d="M8 18h.01" />
      <path d="M12 18h.01" />
      <path d="M16 18h.01" />
    </svg>
  )
}
